#!/bin/bash

# Quran Pulse - Manual Double Deployment Guide
echo "🚀 Quran Pulse Double Deployment Guide"

echo "📋 Step 1: Go to Vercel"
echo "   1. Open https://vercel.com"
echo "   2. Login with GitHub (crnmnwtf@gmail.com)"
echo "   3. Click 'New Project'"

echo ""
echo "📦 Step 2: Deploy Primary"
echo "   1. Find 'Quran-Pulse' repository"
echo "   2. Click 'Import'"
echo "   3. Configure:"
echo "      - Project Name: quran-pulse-primary"
echo "      - Framework: Next.js (auto-detected)"
echo "   4. Add Environment Variables:"
echo "      - NEXT_PUBLIC_APP_URL=https://quran-pulse-primary.vercel.app"
echo "      - NEXTAUTH_URL=https://quran-pulse-primary.vercel.app"
echo "      - GLM_API_KEY=e785716f55ce4b97b0e3705168cfe29d.j0GJj40OLerXMt1l"
echo "   5. Click 'Deploy'"

echo ""
echo "📦 Step 3: Deploy Backup"
echo "   1. After primary deployment, click 'New Project' again"
echo "   2. Find 'Quran-Pulse' repository again"
echo "   3. Click 'Import'"
echo "   4. Configure:"
echo "      - Project Name: quran-pulse-backup"
echo "      - Framework: Next.js (auto-detected)"
echo "   5. Add Environment Variables:"
echo "      - NEXT_PUBLIC_APP_URL=https://quran-pulse-backup.vercel.app"
echo "      - NEXTAUTH_URL=https://quran-pulse-backup.vercel.app"
echo "      - GLM_API_KEY=e785716f55ce4b97b0e3705168cfe29d.j0GJj40OLerXMt1l"
echo "   6. Click 'Deploy'"

echo ""
echo "🎯 Expected URLs:"
echo "   🌍 Primary: https://quran-pulse-primary.vercel.app"
echo "   🌍 Backup: https://quran-pulse-backup.vercel.app"

echo ""
echo "📱 Features Available on Both Deployments:"
echo "   🎨 Theme Support (Light/Dark/System)"
echo "   📚 Digital Iqra Books 1-6"
echo "   🎤 AI Audio Analysis (GLM Powered)"
echo "   📊 Progress Dashboard"
echo "   🏆 Badge & Achievement System"
echo "   🎯 Assessment Mode"
echo "   📖 Tajwid Visualization"
echo "   🌐 Responsive Design"

echo ""
echo "⏱️  Timeline:"
echo "   📦 Primary Deployment: 3-5 minutes"
echo "   📦 Backup Deployment: 3-5 minutes"
echo "   🧪 Testing: 2-3 minutes"
echo "   🎉 Total: ~10-15 minutes"

echo ""
echo "🔗 Quick Links:"
echo "   🌐 Vercel: https://vercel.com"
echo "   📚 GitHub: https://github.com/crnmnwtf/Quran-Pulse"
echo "   📱 Documentation: /DEPLOY_INSTRUCTIONS.md"

echo ""
echo "🎊 Follow these steps for successful double deployment!"